/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PaulLib;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}

// import java.lang.annotation.Documented;
// import java.lang.annotation.ElementType;
// import java.lang.annotation.Inherited;
// import java.lang.annotation.Retention;
// import java.lang.annotation.RetentionPolicy;
// import java.lang.annotation.Target;

// @Retention(RetentionPolicy.CLASS)
// @Inherited
// @Documented
// @Target(ElementType.TYPE)
// public @interface Customannotation{

// }